@host=http://localhost:5133

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstname": "kouumss",
    "lastname": "messaoudi",
    "email": "kouumss@gmail.com",
    "password": "kouumss"
}