@host=http://localhost:5133

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstname": "batman",
    "lastname": "messaoudi",
    "email": "batman@gmail.com",
    "password": "batman"
}